version: 3

env:
  SLN_FILE: ./api/src/ClashRoyaleManager.sln
  APPLICATION_PROJECT: ./api/src/ClashRoyaleManage.Application/ClashRoyaleManage.Application.csproj
  INFRAESTRUCTURE_PROJECT: ./api/src/ClashRoyaleManage.Infraestructure/ClashRoyaleManage.Infraestructure.csproj
  DOMAIN_PROJECT: ./api/src/ClashRoyaleManage.Domain/ClashRoyaleManage.Domain.csproj
  API_PROJECT: ./api/src/ClashRoyaleManager.Api/ClashRoyaleManager.Api.csproj

tasks:
  restore:
    cmds:
      - dotnet restore "{{.SLN_FILE}}"
  
  ef:
      # $timestamp = Get-Date -Format "yyyyMMddHHmmss"
      # dotnet ef migrations add "Migration$timestamp" --project "{{.API_PROJECT}}" --context DefaultDbContext --output-dir Migrations/SqliteMigrations
    cmd: |
      dotnet ef migrations add "AddCodeToPlayerMigration" --project "{{.INFRAESTRUCTURE_PROJECT}}" --context DefaultDbContext --output-dir Migrations/SqliteMigrations
      dotnet ef database update --project "{{.API_PROJECT}}"

  ef-update:
    - dotnet ef database update --project "{{.API_PROJECT}}"
  
  ef-remove:
    - dotnet ef migrations remove --project "{{.INFRAESTRUCTURE_PROJECT}}"

  build:
    - dotnet build "{{.API_PROJECT}}" --no-restore
  
  run:
    - dotnet run --project "{{.API_PROJECT}}"
  